# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Tim Baumgärtner
description: >- # this means to ignore newlines until "baseurl:"
  Tim Baumgärtner's personal website.
baseurl: "/" # the subpath of the site
url: "https://timbmg.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-picture.jpg
google_analytics: "UA-134672665-1"

header:
  pages:
    - name: About
      slug: /
    - name: Publications
      slug: /publications
    - name: CV
      slug: /cv

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: baumgaertner.t@gmail.com
      link: mailto:baumgaertner.t@gmail.com
  follow:
    - name: Twitter
      link: https://twitter.com/timbmg
      username: "@timbmg"
    - name: LinkedIn
      link: https://linkedin.com/in/timbmg
    - name: GitHub
      link: http://github.com/timbmg

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
